steps:
  - name: python
    entrypoint: python
    args: ["FROM", "python:3.10"]
  - name: python
    entrypoint: python
    args: ["ADD", ".", "/app"]
  - name: python
    entrypoint: python
    args: ["WORKDIR", "/app"]
  - name: python
    entrypoint: python
    args: ["pip", "install", "-r", "requirements.txt"]
  - name: python
    entrypoint: python
    args:
      ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args: ["app", "deploy", "dispatch.yaml"]
